flutter: 3.13.8 -> 3.16.4

diff --git a/pkgs/development/compilers/flutter/patches/flutter3/disable-auto-update.patch b/pkgs/development/compilers/flutter/patches/flutter3/disable-auto-update.patch
--- a/pkgs/development/compilers/flutter/patches/flutter3/disable-auto-update.patch
+++ b/pkgs/development/compilers/flutter/patches/flutter3/disable-auto-update.patch
@@ -1,14 +1,29 @@
 diff --git a/bin/internal/shared.sh b/bin/internal/shared.sh
-index 3532c23114..25dfcae4c7 100644
+index 2a47642..ee8f078 100644
 --- a/bin/internal/shared.sh
 +++ b/bin/internal/shared.sh
-@@ -229,8 +229,6 @@ function shared::execute() {
+@@ -223,15 +223,6 @@ function shared::execute() {
+     >&2 echo "Error: Unable to find git in your PATH."
      exit 1
    fi
+-  # Test if the flutter directory is a git clone (otherwise git rev-parse HEAD
+-  # would fail)
+-  if [[ ! -e "$FLUTTER_ROOT/.git" ]]; then
+-    >&2 echo "Error: The Flutter directory is not a clone of the GitHub project."
+-    >&2 echo "       The flutter tool requires Git in order to operate properly;"
+-    >&2 echo "       to install Flutter, see the instructions at:"
+-    >&2 echo "       https://flutter.dev/get-started"
+-    exit 1
+-  fi
  
--  upgrade_flutter 7< "$PROG_NAME"
--
    BIN_NAME="$(basename "$PROG_NAME")"
+ 
+@@ -251,7 +242,6 @@ function shared::execute() {
+   # and will corrupt each others' downloads.
+   #
+   # SHARED_NAME itself is prepared by the caller script.
+-  upgrade_flutter 7< "$SHARED_NAME"
+ 
    case "$BIN_NAME" in
      flutter*)
 diff --git a/packages/flutter_tools/lib/src/cache.dart b/packages/flutter_tools/lib/src/cache.dart
