kakoune-lsp: 16.0.0 -> 17.1.1

diff --git a/pkgs/by-name/ka/kakoune-lsp/Use-full-Perl-path.patch b/pkgs/by-name/ka/kakoune-lsp/Use-full-Perl-path.patch
--- a/pkgs/by-name/ka/kakoune-lsp/Use-full-Perl-path.patch
+++ b/pkgs/by-name/ka/kakoune-lsp/Use-full-Perl-path.patch
@@ -1,31 +1,46 @@
-From b93660cfa8a80a5e5bf72e1f06fb7bf95272c7e4 Mon Sep 17 00:00:00 2001
-From: PoweredByPie <poweredbypie@users.noreply.github.com>
-Date: Fri, 8 Dec 2023 04:39:01 -0800
+From e03d7653823d2f6903f795ce30515088241054c3 Mon Sep 17 00:00:00 2001
+From: embr <git@liclac.eu>
+Date: Mon, 12 Aug 2024 19:06:57 +0200
 Subject: [PATCH] Use full Perl path
 
+Based on this patch by PoweredByPie: https://github.com/NixOS/nixpkgs/blob/33c8b1a7202d4c22d74f4db73666e9a868069d2c/pkgs/by-name/ka/kakoune-lsp/Use-full-Perl-path.patch
 ---
- rc/lsp.kak | 7 +------
- 1 file changed, 1 insertion(+), 6 deletions(-)
+ rc/lsp.kak | 13 ++-----------
+ 1 file changed, 2 insertions(+), 11 deletions(-)
 
 diff --git a/rc/lsp.kak b/rc/lsp.kak
-index d695a2e..7c6a436 100644
+index 306b405..78e9374 100644
 --- a/rc/lsp.kak
 +++ b/rc/lsp.kak
-@@ -2339,11 +2339,6 @@ define-command -hidden lsp-snippets-insert-completion -params 1 %{ evaluate-comm
+@@ -280,12 +280,8 @@ define-command -hidden lsp-menu -params 1.. %{
+ }
+ define-command -hidden lsp-menu-impl %{
+     evaluate-commands %sh{
+-        if ! command -v perl > /dev/null; then
+-            echo "lsp-show-error %{'perl' must be installed to use the 'lsp-menu' command}"
+-            exit
+-        fi
+         echo >$kak_command_fifo "echo -to-file $kak_response_fifo -quoting kakoune -- %reg{a}"
+-        perl < $kak_response_fifo -we '
++        @perlPath@/bin/perl < $kak_response_fifo -we '
+             use strict;
+             my $Q = "'\''";
+             my @args = ();
+@@ -2467,11 +2463,6 @@ define-command -hidden lsp-snippets-insert-completion -params 1 %{ evaluate-comm
  }}
  
  define-command lsp-snippets-insert -hidden -params 1 %[
 -    evaluate-commands %sh{
--        if ! command -v perl > /dev/null 2>&1; then
--            printf "fail '''perl'' must be installed to use the ''snippets-insert'' command'"
+-        if ! command -v perl > /dev/null; then
+-            printf "fail %{'perl' must be installed to use the 'lsp-snippets-insert' command'}"
 -        fi
 -    }
      evaluate-commands -draft -save-regs '^"' %[
          set-register '"' %arg{1}
          execute-keys <a-P>
-@@ -2397,7 +2392,7 @@ define-command lsp-snippets-insert -hidden -params 1 %[
- 
+@@ -2526,7 +2517,7 @@ define-command lsp-snippets-insert -hidden -params 1 %[
  define-command -hidden lsp-snippets-insert-perl-impl %[
+     set-register x nop
      evaluate-commands %sh[ # $kak_quoted_selections
 -        perl -e '
 +        @perlPath@/bin/perl -e '
@@ -33,5 +48,5 @@ index d695a2e..7c6a436 100644
  use warnings;
  use Text::ParseWords();
 -- 
-2.42.0
+2.45.1
 
